### ISSUE TITLE
Example with SASS

### ISSUE THREAD

**Issue by microcipcip** [retyui/group-css-media-queries-loader#1]
Are you able to combine this plugin with nested media queries in SASS? I am getting this error:

```
ERROR in ./~/css-loader!./~/sass-loader!./~/postcss-loader!./~/group-css-media-queries-loader!./src/style.scss
Module build failed: Error: undefined:10:2: missing '}'
    at error (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:62:15)
    at declarations (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:259:26)
    at rule (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:560:21)
    at rules (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:117:70)
    at stylesheet (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:81:21)
    at module.exports (C:\xampp\htdocs\webpacktest\node_modules\css\lib\parse\index.js:564:20)
    at Object.module.exports (C:\xampp\htdocs\webpacktest\node_modules\group-css-media-queries\index.js:12:14)
 @ ./src/style.scss 4:14-216
```

My config is as follow....

```
module: {
        loaders: [
            { test: /\.scss$/, loader: 'style!css!sass!postcss!group-css-media-queries' }
        ]
    },
```

**Comment by retyui** [comment]
Edit your conf 

```
module: {
        loaders: [
            { test: /\.scss$/, loader: 'style!css!postcss!group-css-media-queries!sass' }
        ]
    },
```
